sudo: required

notifications:
  email: false

language: go


services:
  - docker
  - mongodb
  - postgresql

addons:
  postgresql: 9.6
  apt:
    sources:
    - mongodb-3.0-precise
    packages:
    - freetds-bin
    - mongodb-org-server
    - mongodb-org-shell

before_install:
  - sudo service mysql stop
  - docker pull microsoft/mssql-server-linux:latest
  - docker pull mysql:5.7
  - docker run -d -e 'ACCEPT_EULA=Y' -e 'SA_PASSWORD=my$Password' --name mssql -p 1433:1433 -d microsoft/mssql-server-linux:latest
  - docker run -d -e "MYSQL_USER=upperio_tests" -e "MYSQL_PASSWORD=upperio_secret" -e "MYSQL_ALLOW_EMPTY_PASSWORD=1" -e "MYSQL_DATABASE=upperio_tests" -p 3306:3306 --name mysql mysql:5.7
  - docker ps -a
  - sleep 30

env:
  global:
    - MAKEFLAGS="-j4"
    - GOARCH=amd64
    - DB_HOST=127.0.0.1

install:
  - mkdir -p $GOPATH/src/upper.io
  - mv $PWD $GOPATH/src/upper.io/db.v3
  - cd $GOPATH/src/upper.io/db.v3
  - go get -t -v -d ./...
  - go get -v github.com/cznic/ql/ql
  - export TRAVIS_BUILD_DIR=$GOPATH/src/upper.io/db.v3

before_script:
  - docker exec -it mysql bash -c 'mysql_tzinfo_to_sql /usr/share/zoneinfo | mysql -u root mysql'

#script:
#  - ${TEST_CMD}

matrix:
  include:

    - name: "benchmark"
      go:
        - "1.8"
        - "1.9"
      script:
        - make benchmark test-main

    - name: "postgresql"
      go:
        - "1.8"
        - "1.9"
      script:
        - make -C postgresql test
